#!/usr/bin/env python3
"""
Daily Tech Brief Generator
Pulls trending repos from GitHub, analyzes them, writes a markdown brief.
Pushes to frechd/automaton-zero-cost-guide/daily-brief/
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).parent.parent.resolve()
BRIEF_DIR = REPO_ROOT / "daily-brief"
BRIEF_DIR.mkdir(exist_ok=True)

# ── Config ──────────────────────────────────────────────────────────
LANGUAGES = ["python", "typescript", "rust", "go", "javascript"]
REPOS_PER_LANG = 3
DAYS_BACK = 7

HEADERS = {
    "Accept": "application/vnd.github.v3+json",
    "User-Agent": "frech-daily-brief/1.0",
}

# ── Helpers ─────────────────────────────────────────────────────────
def run(cmd: list[str], cwd=None) -> str:
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    if r.returncode != 0:
        print(f"[ERR] {' '.join(cmd)}: {r.stderr}", file=sys.stderr)
    return r.stdout.strip()

def fetch_trending(language: str, days: int, limit: int) -> list[dict]:
    since = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")
    q = f"created:>{since}+language:{language}"
    url = f"https://api.github.com/search/repositories?q={q}&sort=stars&order=desc&per_page={limit}"
    try:
        resp = requests.get(url, headers=HEADERS, timeout=30)
        resp.raise_for_status()
        return resp.json().get("items", [])
    except Exception as e:
        print(f"[ERR] fetch {language}: {e}", file=sys.stderr)
        return []

def fetch_releases(full_name: str) -> list[dict]:
    url = f"https://api.github.com/repos/{full_name}/releases?per_page=3"
    try:
        resp = requests.get(url, headers=HEADERS, timeout=15)
        if resp.status_code == 404:
            return []
        resp.raise_for_status()
        return resp.json()
    except Exception:
        return []

def write_brief(language: str, repos: list[dict]) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    slug = f"{today}-{language}"
    filepath = BRIEF_DIR / f"{slug}.md"

    lines = [
        f"# Daily Brief — {language.upper()} — {today}",
        "",
        f"_Auto-generated by Frech. Scanned {len(repos)} trending repos created in the last {DAYS_BACK} days._",
        "",
    ]

    for i, repo in enumerate(repos, 1):
        name = repo.get("full_name", "unknown/unknown")
        stars = repo.get("stargazers_count", 0)
        desc = repo.get("description") or "(no description)"
        url = repo.get("html_url", "")
        created = repo.get("created_at", "")[:10]
        topics = repo.get("topics", [])
        license_ = (repo.get("license") or {}).get("spdx_id", "?")

        releases = fetch_releases(name)
        release_info = ""
        if releases:
            latest = releases[0]
            tag = latest.get("tag_name", "?")
            rel_date = latest.get("published_at", "")[:10]
            rel_body = latest.get("body", "") or ""
            rel_summary = rel_body.split("\n")[0][:200] if rel_body else "(no notes)"
            release_info = f"  - **Latest release**: `{tag}` ({rel_date}) — {rel_summary}"

        topic_str = ", ".join(topics[:5]) if topics else "none"

        lines.extend([
            f"## {i}. [{name}]({url})",
            "",
            f"> {desc}",
            "",
            f"- ⭐ Stars: `{stars}` | Created: `{created}` | License: `{license_}`",
            f"- Topics: {topic_str}",
        ])
        if release_info:
            lines.append(release_info)
        lines.append("")

    # Add one-liner analysis per repo (template-based, no LLM needed)
    lines.extend([
        "## Quick Takes",
        "",
    ])
    for repo in repos:
        name = repo.get("full_name", "")
        desc = repo.get("description") or ""
        stars = repo.get("stargazers_count", 0)
        # Simple heuristic analysis
        if stars > 500:
            signal = "🔥 High interest"
        elif stars > 100:
            signal = "📈 Growing"
        else:
            signal = "🌱 Early"
        lines.append(f"- **{name}**: {signal} — {desc[:80]}{'...' if len(desc)>80 else ''}")

    lines.extend([
        "",
        "---",
        "_Generated at {} UTC_".format(datetime.utcnow().strftime("%H:%M")),
    ])

    content = "\n".join(lines)
    filepath.write_text(content, encoding="utf-8")
    return str(filepath)

# ── Main ──────────────────────────────────────────────────────────────
def main():
    print(f"[{datetime.now().isoformat()}] Starting daily brief generation...")

    all_files = []
    for lang in LANGUAGES:
        print(f"  → Fetching {lang}...")
        repos = fetch_trending(lang, DAYS_BACK, REPOS_PER_LANG)
        if repos:
            fpath = write_brief(lang, repos)
            all_files.append(fpath)
            print(f"     Written {fpath}")
        else:
            print(f"     No repos found for {lang}")

    if not all_files:
        print("No briefs generated. Exiting.")
        return

    # Git commit + push
    print("  → Committing...")
    today = datetime.now().strftime("%Y-%m-%d")
    run(["git", "add", "daily-brief/"], cwd=REPO_ROOT)
    run(["git", "commit", "-m", f"daily-brief: {today} auto-generated briefs"], cwd=REPO_ROOT)

    # Use explicit SSH key
    env = os.environ.copy()
    env["GIT_SSH_COMMAND"] = "ssh -i ~/.ssh/id_frech_github -o StrictHostKeyChecking=accept-new"
    result = subprocess.run(
        ["git", "push", "origin", "master"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env=env,
    )
    if result.returncode != 0:
        print(f"[ERR] Push failed: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    print(f"  → Pushed {len(all_files)} briefs to origin/master")
    print("Done.")

if __name__ == "__main__":
    main()
